In [1]:
import pandas as pd
import numpy as np

import sys
sys.path.insert(1, '/Users/robertkammerer/Ironhack/06_Week/Labs_Week_6/Spotify_Project/config.py')
from config import *

ModuleNotFoundError: No module named 'config'

In [2]:
import spotipy
import json
from spotipy.oauth2 import SpotifyClientCredentials

#Initialize SpotiPy with user credentias
sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id= client_id,
                                                           client_secret= client_secret_id))

### get some more tracks to add to nohot.csv

In [3]:
def call_playlist(username, playlist_id):    
    
    #step1

    playlist_features_list = ["Artist","Song"]
    
    playlist_df = pd.DataFrame(columns = playlist_features_list)
    
    #step2
    
    #playlist = sp.user_playlist_tracks(creator, playlist_id)["items"]
    
    results = sp.user_playlist_tracks(username,playlist_id)
    playlist = results['items']
    while results['next']:
        results = sp.next(results)
        playlist.extend(results['items'])
    
    for track in playlist:
        # Create empty dict
        playlist_features = {}
        # Get metadata
        playlist_features["Artist"] = track["track"]["album"]["artists"][0]["name"]
        playlist_features["Song"] = track["track"]["name"]
        
        # Concat the dfs
        track_df = pd.DataFrame(playlist_features, index = [0])
        playlist_df = pd.concat([playlist_df, track_df], ignore_index = True)

    #Step 3
        
    return playlist_df

In [4]:
songs2016 = call_playlist("1199301642","1r3n1hu8A0bMa1dTZxNueL")
songs2016

             Artist                Song
0         Fid Mella             Marling
1                AZ          The Format
2     Smif-N-Wessun     Born and Raised
3             Drake       Know Yourself
4        Kool Savas  Und dann kam Essah
..              ...                 ...
248  The Avalanches     Frankie Sinatra
249        Bumcello       Beautiful You
250  Princess Nokia              Tomboy
251           Giggs            Lock Doh
252  Kendrick Lamar             HUMBLE.

[253 rows x 2 columns]

In [5]:
songs2017 = call_playlist("1199301642","4QDxSpz7vwFuPjb116dN81")
songs2017

              Artist                            Song
0       Busta Rhymes  AAAHHHH!!! (feat. Swizz Beatz)
1            J. Cole                  everybody dies
2          070 Shake                    Trust Nobody
3       Jalen Santoy                        Foreplay
4               Ki-2          Drug Dealers & Dancers
..               ...                             ...
378  WESTSIDE BOOGIE         Violence (feat. Masego)
379           G-Eazy                        No Limit
380          Olexesh                        Rolexesh
381  Statik Selektah                       Shakem Up
382         OverDoz.                       Last Kiss

[383 rows x 2 columns]

In [6]:
songs2018 = call_playlist("1199301642","43Kh9KoENRk0Slwj9vJsKI")
songs2018

             Artist                            Song
0        Bruno Mars  Finesse - Remix; feat. Cardi B
1    Kendrick Lamar        All The Stars (with SZA)
2              Ellz                           Bando
3         Mac Lucci          Friday On The Westside
4       Purple City                          My Way
..              ...                             ...
352             Bas     Pinball II (feat .Correy C)
353            Russ                    Nobody Knows
354     Capital Bra                         Benzema
355          Hopsin                         Low-Key
356    Big K.R.I.T.                     4 Tha Three

[357 rows x 2 columns]

In [7]:
songs2019 = call_playlist("1199301642","3zJYIKdOsbofPhDKEoY4tE")
songs2019

              Artist                                               Song
0             Kwam.E                                       Nothin` less
1           Elaquent                                            Onigiri
2      Stephen Smith                                       Nobody Knows
3    Steuerfreimoney                                   Hamburger Schule
4             LGoony                                               Zeit
..               ...                                                ...
411       Kali Uchis  After The Storm (feat. Tyler, The Creator & Bo...
412        YNW Melly             Mixed Personalities (feat. Kanye West)
413      Manu Crooks                                              Fuego
414           Cordae                                         Old niggas
415    Elijah Waters                                       Battery Acid

[416 rows x 2 columns]

In [8]:
songs2020 = call_playlist("1199301642","55l1TLDGPSjf29bJ0YqbFA")
songs2020

                 Artist                                               Song
0                    T3                                              Relax
1            Mac Miller                                          Good News
2                Common        My Fancy Free Future Love - Tom Misch Remix
3              Elaquent                                         Guidelines
4             070 Shake                                  Guilty Conscience
..                  ...                                                ...
347           Lil Wayne                   B.B. King Freestyle (with Drake)
348  Cult Of The Damned                                           Gung Foo
349          Caleborate                                          Caught Up
350       Future Utopia  Children Of The Internet - Remix feat. Joey Ba...
351     Statik Selektah                           Time (feat. Jack Harlow)

[352 rows x 2 columns]

In [9]:
house= call_playlist("1199301642","3FZHgry0J2O6Gi5FIso2hD")
house

                   Artist                                            Song
0   Zepherin Saint & Mr V                     Dance Release - Tribe Vocal
1           Cincitys Yazz             Cincitys Yazz - Yaya (Original Mix)
2         Various Artists  Crazy (Zepherin Saint Vocal Mix) [feat. Thiwe]
3           Matthew Bandy                  Zepherin Saint Tribe Vocal Mix
4            Boddhi Satva      Elengi feat. Zé Pequenio & Heritier - Main
..                    ...                                             ...
93              Afefe Iku                                    Mirror Dance
94                   Omar                                         Dancing
95            Afro Medusa                                         Pasilda
96            Alicia Keys                  In Common - Black Coffee Remix
97      Yukihiro Fukutomi                                     The Tambour

[98 rows x 2 columns]

In [10]:
oldies = pd.read_csv("/Users/robertkammerer/Ironhack/06_Week/Labs_Week_6/Spotify_Project/Data/nohit.csv")
oldies

              Artist                                           Song
0    Backstreet Boys                   Everybody (Backstreets Back)
1          MC Hammer                             U Can't Touch This
2    Michael Jackson                                 Black Or White
3             Coolio                             Gangsta's Paradise
4             Hanson                                         Mmmbop
..               ...                                            ...
992           Akufen  Deck the House (Herbert’s Stop Like This Mix)
993            Woods                                        Rain On
994          Unwound                                      Scarlette
995          N*E*R*D            Run to the Sun (Electronic Version)
996     The Big Pink                                         Velvet

[997 rows x 2 columns]

In [11]:
rock= call_playlist("1199301642","29RO0worSJjuu77SI7GXoR")
rock

               Artist                                          Song
0               AC/DC                   You Shook Me All Night Long
1       Guns N' Roses                         Welcome To The Jungle
2         Def Leppard       Pour Some Sugar On Me - Remastered 2017
3           Van Halen                          Jump - 2015 Remaster
4               Queen  Another One Bites The Dust - Remastered 2011
..                ...                                           ...
361  Three Days Grace                   I Hate Everything About You
362      Rise Against                                        Savior
363      Fall Out Boy                        Sugar, We're Goin Down
364        The Ataris                            The Boys of Summer
365            P.O.D.                           Youth of the Nation

[366 rows x 2 columns]

In [13]:
classic= call_playlist("1199301642","0dlEyIqfuzinIRhwrj3ZPN")
classic

                     Artist                                               Song
0      Ludwig van Beethoven  Symphony No. 6 in F Major, Op. 68 "Pastoral": ...
1    Angelo Nicola Giuliano                                     Angel's prayer
2   Wolfgang Amadeus Mozart               Le Nozze di Figaro, K. 492: Sinfonia
3         Riccardo Callisto                         You're Not Alone, I'm Here
4       Camille Saint-Saëns                                           Aquarium
..                      ...                                                ...
67  Wolfgang Amadeus Mozart                        Fantasia in D Minor, K. 397
68          Various Artists                       Delibes: Waltz from Coppélia
69  Nikolai Rimsky-Korsakov      Scheherazade: The Tale of the Kalendar Prince
70           Hector Berlioz  Symphonie fantastique: V. Dream of a Witches' ...
71         Sergei Prokofiev  Romeo and Juliet, Op. 64 / Act 1: Dance Of The...

[72 rows x 2 columns]

In [15]:
techno = call_playlist("1199301642","37i9dQZF1DX6J5NfMJS675")
techno.head()

         Artist                              Song
0  Lilly Palmer                        We Control
1     Eli Brown                           Believe
2       Mha Iri            Open Up - Original Mix
3    NoNameLeft  The Second Law of Thermodynamics
4         HI-LO                     String Theory

In [16]:
pop = call_playlist("1199301642","5rnSpFXLf5Vj5w1QUeqopr")
pop.head()

            Artist           Song
0  Imagine Dragons         Demons
1  Imagine Dragons       Believer
2       The Wanted  Glad You Came
3           Avicii     Wake Me Up
4            Kesha        TiK ToK

In [17]:
nohitfinal = pd.concat([oldies, songs2016, songs2017, songs2018, songs2019, songs2020, house, rock, techno, pop, classic],axis=0)
nohitfinal

                     Artist                                               Song
0           Backstreet Boys                       Everybody (Backstreets Back)
1                 MC Hammer                                 U Can't Touch This
2           Michael Jackson                                     Black Or White
3                    Coolio                                 Gangsta's Paradise
4                    Hanson                                             Mmmbop
..                      ...                                                ...
67  Wolfgang Amadeus Mozart                        Fantasia in D Minor, K. 397
68          Various Artists                       Delibes: Waltz from Coppélia
69  Nikolai Rimsky-Korsakov      Scheherazade: The Tale of the Kalendar Prince
70           Hector Berlioz  Symphonie fantastique: V. Dream of a Witches' ...
71         Sergei Prokofiev  Romeo and Juliet, Op. 64 / Act 1: Dance Of The...

[3509 rows x 2 columns]

In [18]:
nohitfinal.to_csv("/Users/robertkammerer/Ironhack/06_Week/Labs_Week_6/Spotify_Project/Data/nohit_final2.csv",index=False) # added rock, classic, techno, pop